I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 65, in script
    Echo "If you beat me up it'd be murder. I might, might have a chance with a newborn foal! Murder, I said!"
Exception: Sayer 'Echo' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 65, in script
    Echo "If you beat me up it'd be murder. I might, might have a chance with a newborn foal! Murder, I said!"
  File "C:\Users\WhiskeyHorse\Downloads\renpy-6.99.14-sdk\renpy\ast.py", line 615, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\WhiskeyHorse\Downloads\renpy-6.99.14-sdk\renpy\ast.py", line 528, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Echo' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.14.3135
diesel-throwers 1.0
